version: '2.1'

services:
  chainpoint-roughtime:
    build: .
    image: gcr.io/chainpoint-registry/github-chainpoint-chainpoint-roughtime:0e5eb8f388fa4622e325028217d8e57a472b2dcc
    container_name: chainpoint-roughtime
    hostname: roughtime
    restart: on-failure:2
    volumes:
      - ./roughenough.cfg:/roughenough/roughenough.cfg:ro
    ports:
      - "2002:2002/udp"
