version: '2.1'

services:
  chainpoint-roughtime:
    build: .
    image: gcr.io/chainpoint-registry/github-chainpoint-chainpoint-roughtime:latest
    container_name: chainpoint-roughtime
    hostname: roughtime
    restart: on-failure:2
    volumes:
      - ./roughenough.cfg:/roughenough/roughenough.cfg:ro
    ports:
      - "2002:2002/udp"
      - "8000:8000"
